### ISSUE TITLE
Configured debug type 'fs-uae-run' is not supported.

### ISSUE THREAD

**Issue by IstiCusi** [prb28/vscode-amiga-vbcc-example#11]
Building works fine -- but running as described in the readme leads to a  'Configured debug type 'fs-uae-run' is not supported.' 
I hope, that it is not my mistake. I tried with both:

Version: 1.64.0-insider
Commit: 45060913204279d4ecfe0575ca69d68211fb3798
Date: 2022-01-26T05:15:39.013Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64

and with 

Version: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:15:35.620Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64

**Comment by prb28** [comment]
This project is almost abandoned by me since bartman released his extension that is way better for C/C++ development.
With the assembly extension you cannot debug the C part correctly (misses variables values, stacktrace, etc.)
But, you are right, I may at least make it work with new extension version.
I'll do a commit with the new settings.

**Comment by IstiCusi** [comment]
Thanks dear mate -- I think your project is quite nice -- the disadvantage of bartman's plugin is, that it only works for windows, while you provide linux :) -- 
Send the best wishes from Zuerich, Stephan

**Comment by prb28** [comment]
Try to update, that should work better now.

**Comment by IstiCusi** [comment]
Works nicely now ! Thanks a lot dear mate -- in case I find some additonal ideas I give back ... cheers from Zuerich!

**Comment by prb28** [comment]
You are welcome!
